Application Autoscaling Scheduled Action
aws-cloudformation/community-registry-extensions pull request #100
Opened 2022-11-14 15:42 UTC by JohnPreston

Resource `AwsCommunity::ApplicationAutoscaling::ScheduledAction`

Allows to created Scheduled Actions against resources that support ApplicationAutoscaling" and respective dimensions.

Deploying here rather than on my own account.

2022-11-14 15:45 UTC, JohnPreston reviewed
Should change the loglelevel to INFO/ERROR/CRITICAL.
Happy to set as directed.

2022-11-14 15:45 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/src/awscommunity_applicationautoscaling_scheduledaction/handlers.py
> +LOG.setLevel(logging.DEBUG)
```suggestion
LOG.setLevel(logging.CRITICAL)
```

2022-11-14 16:41 UTC, cmgorton commented
Thanks for the contribution @JohnPreston 🙌. We will ping someone on the team to review it soon.

2022-11-14 17:05 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/src/awscommunity_applicationautoscaling_scheduledaction/handlers.py
> +LOG.setLevel(logging.DEBUG)
DEBUG is fine for now, we can change it when we GA the extension.

2022-11-14 17:07 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/src/awscommunity_applicationautoscaling_scheduledaction/handlers.py
> +LOG.setLevel(logging.DEBUG)
Great. Thanks @ericzbeard

2022-11-14 17:24 UTC, ericzbeard requested changes
Need to add a README.md that explains the extension and shows a sample template.

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/.editorconfig
> +# http://editorconfig.org
Is this file something that should be checked in?

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/.gitignore
> +*portal.sso.GetRoleCredentials*.json
Add the zip file created by `cfn submit`.

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +  "description": "Application Autoscaling Scheduled Action.",
Let's expand this a bit and start with "An experimental resource type that..."

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +  "sourceUrl": "https://github.com/johnpreston/awscommunity-applicationautoscaling-scheduledaction",
Switch to this repo.

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*"
Can you add a description that explains the regex?

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +        "ecs:service:DesiredCount",
I'm wondering if we should leave this open, for future compatibility without having to re-deploy the resource.

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +      "enum": [
Same comment as above, if we leave it open, we won't have to change it in the future.

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/resource-role.yaml
> +AWSTemplateFormatVersion: "2010-09-09"
We also need a `resource-role-prod.yaml` that removes the condition and adds `cloudformation:ListExports`. We should probably automate that with a script.

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/resource-test.template
> +AWSTemplateFormatVersion: "2010-09-09"
What's the difference between this and `integ/test.yml` ?

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/src/awscommunity_applicationautoscaling_scheduledaction/handlers.py
> +def rule_exists(session: SessionProxy, model) -> Union[dict, None]:
Did you lint these with `../../config/.pylintrc` ?

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/src/awscommunity_applicationautoscaling_scheduledaction/handlers.py
> +        LOG.error("EndTime")
What happens with the return value if this exception happens?

2022-11-14 17:24 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/inputs/inputs_1_create.json
> +  "ResourceId": "service/cfn-testing/cfn-testing"
I was expecting to see some template variables to reference the setup template.

2022-11-14 17:31 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/.editorconfig
> +# http://editorconfig.org
Maybe not? I find it is very useful to avoid different devs having their own settings, i.e. 4 spaces, tabs, and so on.
Happy to remove it. As said in many other comments, that's out of copy-paste from my own repo/folders.

2022-11-14 17:32 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*"
That's a "copy-paste" from the official documentation.
Should I use `description` to point to the link of that property?

2022-11-14 17:50 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*"
I'm fine with a brief description here instead of a link, or maybe both. Not sure how a long a description can be.

2022-11-14 17:51 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/.editorconfig
> +# http://editorconfig.org
Might be simpler to standardize on `black`.

2022-11-14 17:53 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/awscommunity-applicationautoscaling-scheduledaction.json
> +      "pattern": "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*"
https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html#autoscaling-PutScheduledAction-request-ResourceId

```
Type: String

Length Constraints: Minimum length of 1. Maximum length of 1600.

Pattern: [\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*

Required: Yes
```
Makes me realize I should have Min and Max Length set :thinking:

2022-11-14 18:05 UTC, ericzbeard commented on resources/ApplicationAutoscaling_ScheduledAction/inputs/inputs_1_create.json
> +  "ResourceId": "service/cfn-testing/cfn-testing"
See https://github.com/aws-cloudformation/community-registry-extensions/blob/main/resources/S3_DeleteBucketContents/inputs/inputs_1_create.json and https://github.com/aws-cloudformation/community-registry-extensions/blob/main/resources/S3_DeleteBucketContents/test/setup.yml for an example. The input files can refer to an export from the setup template, so you don't have to hard code any resource names.

2022-11-16 13:44 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/.editorconfig
> +# http://editorconfig.org
That's what I use for everything @ericzbeard

2022-11-16 13:59 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/inputs/inputs_1_create.json
> +  "ResourceId": "service/cfn-testing/cfn-testing"
Ah right, export value used, I see.

2022-11-16 14:05 UTC, JohnPreston commented on resources/ApplicationAutoscaling_ScheduledAction/inputs/inputs_1_create.json
> +  "ResourceId": "service/cfn-testing/cfn-testing"
But then I don't get why we have integ.yml and setup.yml when integ.yml in the S3 example also re-creates a bucket anyways?

2023-05-09 10:58 UTC, JohnPreston commented
Closing due to git snaffoo for clean-ness

2023-05-09 10:58 UTC, closed without merging