Initial Fastly CICD pipeilne and Services:Domain resource
aws-cloudformation/community-registry-extensions pull request #113
Opened 2022-12-13 20:20 UTC by mmaeng

Initial CICD pipeline for fastly and the build for Fastly:Services:Domain

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-14 16:36 UTC, ericzbeard requested changes

2022-12-14 16:36 UTC, ericzbeard commented on release/cicd.yml
> -              - iam:UpdateAssumeRolePolicyDocument
Why was this removed? Pretty sure this will break something.

2022-12-14 16:36 UTC, ericzbeard commented on release/fastly/cicd.yml
> +          Type: SECRETS_MANAGER
We should consolidate on parameter store for values that are not sensitive. I'm using secrets manager for typeConfiguration, which has actual secrets in it.

2022-12-14 16:36 UTC, ericzbeard commented on release/fastly/cicd.yml
> +  StackSetAdministrationRole:
Should be safe to delete the StackSet resources, since we aren't publishing with stack sets any more.

2022-12-14 21:31 UTC, mmaeng commented on release/cicd.yml
> -              - iam:UpdateAssumeRolePolicyDocument
The cloudformation console is saying iam:UpdateAssumeRolePolicyDocument doesn't exist as a property so I removed it.

2022-12-14 21:40 UTC, ericzbeard commented on release/cicd.yml
> -              - iam:UpdateAssumeRolePolicyDocument
Weird, I only added those when I got errors for actions that were missing. I guess it should be `UpdateAssumeRolePolicy`

2022-12-14 21:44 UTC, mmaeng commented on release/fastly/cicd.yml
> +          Type: SECRETS_MANAGER
My main motivation was the built in regional replication for secrets manager.  One less item to maintain but I can switch it.

2022-12-14 21:52 UTC, ericzbeard commented on release/fastly/cicd.yml
> +          Type: SECRETS_MANAGER
We don't need cross region, since we aren't deploying a pipeline per region any more.

2022-12-14 22:52 UTC, ericzbeard requested changes
I just merged the common template and now there's a conflict in the cicd template.

2022-12-14 22:52 UTC, ericzbeard commented on release/cicd.yml
> -              - kms:DeleteKey
Why was this removed?

2022-12-15 01:52 UTC, mmaeng commented on release/cicd.yml
> -              - kms:DeleteKey
Deletekey also doesnt look to be an existing property, it looks to have been replaced with scheduledeletion.

2022-12-15 14:22 UTC, mmaeng commented on release/cicd.yml
> -              - kms:DeleteKey
Let me revert this change for this PR.

2022-12-16 18:29 UTC, mmaeng commented
Included in #116

2022-12-16 18:29 UTC, closed without merging