Adding a new hook that checks if S3 buckets have versioning enabled
aws-cloudformation/community-registry-extensions pull request #131
Opened 2023-01-26 22:09 UTC by shankar-cloud-builder

2023-01-26 23:08 UTC, ericzbeard requested changes

2023-01-26 23:08 UTC, ericzbeard commented on README.md
> +# Static Analysis for Infrastructure as Code to validate against AWS Best Practices
This is the top level readme.

2023-01-26 23:08 UTC, ericzbeard commented on hooks/S3_BucketVersioningCheck/src/awscommunity_s3_versioningcheck/handlers.py
> +    # TODO: put code here
Remove TODOs

2023-01-26 23:08 UTC, ericzbeard commented on hooks/S3_BucketVersioningCheck/src/awscommunity_s3_versioningcheck/handlers.py
> +    # TODO: put code here
Remove TODO

2023-01-26 23:08 UTC, ericzbeard commented on hooks/S3_BucketVersioningCheck/src/awscommunity_s3_versioningcheck/handlers.py
> +        resource_properties = target_model.get("resourceProperties")
Will this code ever be reached?

2023-03-30 18:16 UTC, kddejong commented
Closed in favor of the already existing hook of the same purpose.

2023-03-30 18:16 UTC, closed without merging