Setup snowflake for CICD pipeline
aws-cloudformation/community-registry-extensions pull request #135
Opened 2023-02-01 23:50 UTC by joshuadeanhall

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-01 23:57 UTC, rajdnp approved these changes

2023-02-02 17:02 UTC, ericzbeard requested changes

2023-02-02 17:02 UTC, ericzbeard commented on release/snowflake/cicd.yml
> +  SnowflakeDatabaseDatabaseBuildProjectRole:
This role should reference the common build project policy.
```
ManagedPolicyArns:
        - Fn::ImportValue: !Sub "cep-${Env}-common-build-project-policy"
```

2023-02-02 20:21 UTC, joshuadeanhall commented on release/snowflake/cicd.yml
> +  CommonBuildProjectPolicy:
Removed this.

2023-02-02 20:22 UTC, joshuadeanhall commented on release/snowflake/cicd.yml
> +  SnowflakeDatabaseDatabaseBuildProjectRole:
Modified this to match latest example

2023-02-02 20:22 UTC, joshuadeanhall commented
Updated everything to match the most recent example.

2023-02-02 22:00 UTC, ericzbeard submitted a review, later dismissed

2023-02-02 23:54 UTC, ericzbeard approved these changes

2023-02-02 23:55 UTC, merged