adding new resources to cicd script
aws-cloudformation/community-registry-extensions pull request #137
Opened 2023-02-02 10:36 UTC by lukiwlosek

Adding new resources as mentioned here: https://github.com/aws-ia/cloudformation-github-resource-providers/issues/18

Let me know if I have missed anything and this is the right format, also one thing I was unsure of is the `GITHUB_REPO_ID` value as this needs to be a number not a string, if this has to be as string and fails, this would mean it would have to be changed on the resource side.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-02 17:10 UTC, ericzbeard requested changes

2023-02-02 17:10 UTC, ericzbeard commented on release/github/cicd.yml
> +          Value: 123456789
Change this to "cep-github-repo-id" and I will create a parameter store entry.

2023-02-02 17:12 UTC, ericzbeard commented on release/github/cicd.yml
> +          Value: 123456789
I'll need to test and see what happens with the value if it's submitted as a string.

2023-02-03 09:12 UTC, lukiwlosek commented on release/github/cicd.yml
> +          Value: 123456789
pushed this change

2023-02-03 17:30 UTC, ericzbeard approved these changes

2023-02-03 17:30 UTC, merged

2023-02-03 18:48 UTC, ericzbeard commented
> @lukiwlosek Where do I find the numeric github repo id? I'm used to referring to repos by name.

I think I found it: https://stackoverflow.com/questions/13902593/how-does-one-find-out-ones-own-repo-id