Add AwsCommunity::Resource::Lookup resource type.
aws-cloudformation/community-registry-extensions pull request #190
Opened 2023-04-12 17:41 UTC by mrinaudo-aws

*Issue #, if available:*

*Description of changes:*
Add AwsCommunity::Resource::Lookup resource type.

## Tests excerpts

### Unit tests excerpts
[...]
[INFO] --- jacoco:0.8.9:check (jacoco-check) @ awscommunity-resource-lookup-handler ---
[...]
[INFO] Analyzed bundle 'awscommunity-resource-lookup-handler' with 10 classes
[INFO] All coverage checks have been met.
[...]

## Contract tests excerpts
[...]
13 passed, 2 skipped, 9 deselected, 1 warning in 1021.84s (0:17:01)
[...]

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-13 09:17 UTC, benbridts commented
I like this a lot!

A few feature requests:

-  Can we add a `Serial` or `Trigger` parameter (like [AwsCommunity::Time::Sleep](https://github.com/aws-cloudformation/community-registry-extensions/tree/main/resources/Time_Sleep)), so that you can refresh the value without changing the query (It's not a 100% clear to me from the schema if changing the query triggers a new lookup, so making that more clear might be a good thing too)?
- Would `AwsCommunity::Resource::Lookup` be a better name, if that's the only output it can generate?

And some questions  related to that: 

I think there is also a need for
  - a way to get other properties of a resource. This could be part of this  (there could be a `JmesPathSelectorQuery` and a `JmesPathOutputQuery`, or a separate thing (`AwsCommunity::Resource::Read`).
  - a way to get a list of resources / identifiers / properties (in that case I think it makes more sense to have a `AwsCommunity::CloudControlQuery::List` and `AwsCommunity::CloudControlQuery::Get` resource, and not the two different kinds of JmesPath). (eg. I want all the subnets of one vpc that have the `type=private` tag).

2023-04-13 15:43 UTC, mrinaudo-aws commented
> > * Can we add a `Serial` or `Trigger` parameter [...]
> 
> I am currently looking into adding and testing a `LookupSerialNumber` property in the schema for this.

Added in a new commit.

2023-04-13 16:19 UTC, mrinaudo-aws commented
> > [...] (It's not a 100% clear to me from the schema if changing the query triggers a new lookup, so making that more clear might be a good thing too)?

Added this clarification to the description of the relevant property in the schema in the same new commit as well.

2023-04-13 17:52 UTC, ericzbeard requested changes

2023-04-13 17:52 UTC, ericzbeard commented on resources/Resource_Lookup/awscommunity-resource-lookup.json
> +            "description": "Optional key-value pairs object to associate to the AWS Systems Manager Parameter Store parameter resource, that this resource type uses to persist the lookup result.",
I think I understand what this is for, but the docs need more explanation.

2023-04-13 17:52 UTC, ericzbeard commented on resources/Resource_Lookup/awscommunity-resource-lookup.json
> +           "description": "The ID of the resource lookup action you are performing.",
I don't understand what this is for.

2023-04-13 17:52 UTC, ericzbeard commented on resources/Resource_Lookup/inputs/inputs_1_update.json
> +{
Include the serial number in the input for updates.

2023-04-13 17:52 UTC, ericzbeard commented on resources/Resource_Lookup/src/main/java/com/awscommunity/resource/lookup/BaseHandlerStd.java
> +        return handleRequest(proxy, request, callbackContext != null ? callbackContext : new CallbackContext(),
I would love to see some code comments to tell me what's going on here.

2023-04-13 17:52 UTC, ericzbeard commented on resources/Resource_Lookup/test/integ.yml
> +Parameters:
The integ template shouldn't have params, even if they have defaults. We don't have a mechanism to populate params during integ testing, so they seem to be an unnecessary complication.

2023-04-13 18:12 UTC, mrinaudo-aws commented on resources/Resource_Lookup/awscommunity-resource-lookup.json
> +        "ResourceLookupRoleArn": {
This way users can specify their own IAM role with the policy they wish to use.  There is an example template that describes a role with a read-only policy, but the user might want to use a different policy.

2023-04-13 18:18 UTC, mrinaudo-aws commented on resources/Resource_Lookup/awscommunity-resource-lookup.json
> +            "description": "Optional key-value pairs object to associate to the AWS Systems Manager Parameter Store parameter resource, that this resource type uses to persist the lookup result.",
The `Usage` section in the `README.md` file describe this already and shows an example; however, I will add an additional, dedicated section in that file for the `Tags` property.

2023-04-13 18:24 UTC, mrinaudo-aws commented on resources/Resource_Lookup/examples/example-resource-lookup.template
> +Resources:
`ResourceModel` is only needed in some cases (the parameter description has a link with an explanation).  The user can reuse this example template, and pass values that are not empty (hence, the condition).  See also the `The ResourceModel property` section in the `README.md` file for more context.

2023-04-13 18:39 UTC, mrinaudo-aws commented on resources/Resource_Lookup/test/integ.yml
> +Parameters:
I have done it this way because since you can use default values without passing them, the developer can easily use this template in their account to pass different values for a rapid test on other queries and values (this is the method I also use).  I had also added a section called `Integration tests` in the README.md` that does not directly call parameters, but shows the intent for end-to-end testing extended to the developer.  For this reason, I'd like to leave the template as it is, unless there are concerns.

2023-04-13 19:31 UTC, mrinaudo-aws commented on resources/Resource_Lookup/src/main/java/com/awscommunity/resource/lookup/ReadHandler.java
> +    protected ProgressEvent<ResourceModel, CallbackContext> handleRequest(final AmazonWebServicesClientProxy proxy,
Will add more comments - thanks!

2023-04-13 20:31 UTC, mrinaudo-aws commented on resources/Resource_Lookup/awscommunity-resource-lookup.json
> +           "description": "The ID of the resource lookup action you are performing.",
Adding more info - thank you!

2023-04-13 22:27 UTC, mrinaudo-aws commented
Added changes - no code changes made.  Contract tests excerpts:

```
13 passed, 2 skipped, 9 deselected, 1 warning
```

2023-04-14 03:51 UTC, mrinaudo-aws commented
Small schema and docs updates made.  No code changes.  Contract tests excerpts:

```
13 passed, 2 skipped, 9 deselected, 1 warning
```

2023-04-14 10:11 UTC, mrinaudo-aws commented
Another small documentation-related update made, in the schema. No code changes. Contract tests excerpts:

```
13 passed, 2 skipped, 9 deselected, 1 warning
```

2023-04-14 13:29 UTC, mrinaudo-aws commented
Made additional changes to the README.md file.  Please review - thanks!

2023-04-14 20:05 UTC, mrinaudo-aws commented
Added changes for using a namespace for the primary ID.  Tests excerpts:

```
[...]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.awscommunity.resource.lookup.LookupHelperTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.508 s - in com.awscommunity.resource.lookup.LookupHelperTest
[INFO] Running com.awscommunity.resource.lookup.ReadHandlerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.779 s - in com.awscommunity.resource.lookup.ReadHandlerTest
[INFO] Running com.awscommunity.resource.lookup.CreateHandlerResourceLookupTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 s - in com.awscommunity.resource.lookup.CreateHandlerResourceLookupTest
[INFO] Running com.awscommunity.resource.lookup.CreateHandlerTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 s - in com.awscommunity.resource.lookup.CreateHandlerTest
[INFO] Running com.awscommunity.resource.lookup.ListHandlerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 s - in com.awscommunity.resource.lookup.ListHandlerTest
[INFO] Running com.awscommunity.resource.lookup.UpdateHandlerTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 s - in com.awscommunity.resource.lookup.UpdateHandlerTest
[INFO] Running com.awscommunity.resource.lookup.ClientBuilderTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.44 s - in com.awscommunity.resource.lookup.ClientBuilderTest
[INFO] Running com.awscommunity.resource.lookup.TagHelperTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in com.awscommunity.resource.lookup.TagHelperTest
[INFO] Running com.awscommunity.resource.lookup.CreateHandlerStabilizeTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in com.awscommunity.resource.lookup.CreateHandlerStabilizeTest
[INFO] Running com.awscommunity.resource.lookup.DeleteHandlerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 s - in com.awscommunity.resource.lookup.DeleteHandlerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 63, Failures: 0, Errors: 0, Skipped: 0
[...]
```

```
[...]
INFO] --- jacoco:0.8.9:check (jacoco-check) @ awscommunity-resource-lookup-handler ---
[...]
[INFO] Analyzed bundle 'awscommunity-resource-lookup-handler' with 10 classes
[INFO] All coverage checks have been met.
[...]
```

```
13 passed, 2 skipped, 9 deselected, 1 warning
```

2023-04-14 21:19 UTC, ericzbeard approved these changes

2023-04-14 21:19 UTC, merged