Java restypes pipeline patch
aws-cloudformation/community-registry-extensions pull request #205
Opened 2023-05-03 14:57 UTC by mrinaudo-aws

*Issue #, if available:*

*Description of changes:*
Update docs, and role setup used as part of the CI/CD logic.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-03 16:19 UTC, ericzbeard requested changes

2023-05-03 16:19 UTC, ericzbeard commented on release/awscommunity/cicd.yml
> +            Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*-awscommunity-resource-loo*'
This should be combined with the entry above, and we need to give the integ and setup roles physical names in order for this to work.

2023-05-03 16:27 UTC, mrinaudo-aws commented on release/awscommunity/cicd.yml
> +            Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*-awscommunity-resource-loo*'
An end-to-end test on my copy of the pipeline succeeded with those settings, but if we are concerned that this approach might not be consistent here, I can look into having set names for roles (that I avoided to lower the possibility of name clashing).

2023-05-03 16:31 UTC, ericzbeard commented on release/awscommunity/cicd.yml
> +            Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*-awscommunity-resource-loo*'
You could include Env as a parameter. Something like `cep-resource-lookup-integ-${Env}`.

2023-05-03 17:26 UTC, mrinaudo-aws commented on release/awscommunity/cicd.yml
> +            Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*-awscommunity-resource-loo*'
@ericzbeard I am pushing some test changes to my fork.  To avoid confusion in the interim, I am converting this PR to a draft.

2023-05-03 23:07 UTC, mrinaudo-aws commented
Hi @ericzbeard - let me actually revert the PR to draft - want to continue testing on my sandbox pipeline a bit more.

2023-05-04 17:45 UTC, mrinaudo-aws commented
> Hi @ericzbeard - let me actually revert the PR to draft - want to continue testing on my sandbox pipeline a bit more.

@ericzbeard - ready for review.

2023-05-04 17:47 UTC, ericzbeard commented on resources/Resource_Lookup/test/integ.yml
> +    Default: beta
Does the buildspec set this?

2023-05-04 17:48 UTC, mrinaudo-aws commented on resources/Resource_Lookup/test/integ.yml
> +    Default: beta
It does not - integ runs on beta, and I set it by default as it is.

2023-05-04 17:49 UTC, ericzbeard approved these changes

2023-05-04 17:50 UTC, merged