Hook lambda invoker
aws-cloudformation/community-registry-extensions pull request #213
Opened 2023-05-26 22:58 UTC by ericzbeard

This PR introduces a Hook that serves as a central point to register Lambda functions that do the actual compliance checks.

2023-06-06 20:01 UTC, mmaeng commented on config/.pylintrc
> +overgeneral-exceptions=buitlins.BaseException,
I think you have a typo here

2023-06-06 20:28 UTC, mmaeng approved these changes
LGTM

2023-06-07 17:54 UTC, mrinaudo-aws requested changes
Thank you, @ericzbeard!  I have added suggestions, and feedback.

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/README.md
> +file is used to tell the hook the Arn of the DynamoDB table that contains a list of
```suggestion
file is used to tell the hook the ARN of the DynamoDB table that contains a list of
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/compliance.yaml
> +        This table holds a list of Lambda Arns that will be invoked by the
```suggestion
        This table holds a list of ARNs of Lambda functions that will be invoked by the
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/module.yaml
> +  This module is invoked from `compliance.yaml` to create a lambda
```suggestion
  This module is invoked from `compliance.yaml` to create a Lambda 
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/module.yaml
> +  function and add the arn to the registration table. This module
```suggestion
  function and add the ARN to the registration table. This module 
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/validate.py
> +the compliance lambda functions, to make sure their code is valid before
```suggestion
the compliance Lambda functions, to make sure their code is valid before 
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/validate.py
> +to get the list of lambda function arns, decomposes the template into
```suggestion
to get the list of Lambda function ARNs, decomposes the template into 
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/validate.py
> +won't know the arn yet, and if your compliance lambda validates a specific arn,
```suggestion
won't know the arn yet, and if your compliance lambda validates a specific ARN, 
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/samples/rain/validate.py
> +    # Scan the DDB table to get the Lambda Arns
```suggestion
    # Scan the DDB table to get the Lambda ARNs
```

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/src/awscommunity_lambda_invoker/invoker.py
> +        except Exception as lamex:
Can we use an idiomatic name for the variable?

2023-06-07 17:54 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/test/setup.yaml
> +        hook. The table holds a list of Lambda Arns that will be invoked in
```suggestion
        hook. The table holds a list of ARNs of Lambda functions that will be invoked in
```

2023-06-07 20:00 UTC, ericzbeard commented on hooks/Lambda_Invoker/README.md
> +key consiting of one attribute, 'lambda\_arn'.
The backslash is necessary for markdown.

2023-06-07 20:01 UTC, ericzbeard commented on hooks/Lambda_Invoker/.rpdk-config
> +    "typeName": "AwsCommunity::Lambda::Invoker",
Maybe `AwsCommunity::Compliance::LambdaInvoker` ?

2023-06-07 20:19 UTC, ericzbeard commented on .vscode/settings.json
> +{
We need to use that file specifically or the checks will fail.

2023-06-07 20:25 UTC, kddejong commented on hooks/Lambda_Invoker/src/awscommunity_lambda_invoker/invoker.py
> +            print(resp)
why not logger?

2023-06-07 20:44 UTC, ericzbeard commented on hooks/Lambda_Invoker/src/awscommunity_lambda_invoker/invoker.py
> +            print(resp)
Fixing those in the next PR.

2023-06-07 20:44 UTC, ericzbeard commented on hooks/Lambda_Invoker/.rpdk-config
> +    "typeName": "AwsCommunity::Lambda::Invoker",
@kddejong what do you think about the name?

2023-06-07 20:46 UTC, ericzbeard commented on hooks/Lambda_Invoker/src/awscommunity_lambda_invoker/invoker.py
> +        except Exception as lamex:
Doesn't seem important here. I would have made this a one liner but I wanted to see output printed.

2023-06-07 20:47 UTC, kddejong approved these changes

2023-06-08 15:02 UTC, mrinaudo-aws commented on hooks/Lambda_Invoker/.rpdk-config
> +    "typeName": "AwsCommunity::Lambda::Invoker",
Hi @ericzbeard - sorry for delays in responses - I think the `AwsCommunity::Compliance::LambdaInvoker` name you proposed above makes more sense.

2023-06-14 17:01 UTC, merged