Add S3_AccessControl hook.
aws-cloudformation/community-registry-extensions pull request #238
Opened 2023-09-21 19:29 UTC by mrinaudo-aws

*Issue #, if available:*

*Description of changes:*
Add S3_AccessControl hook.

## Unit tests excerpts
```
[...]
[INFO] Running com.awscommunity.s3.accesscontrol.PreUpdateHookHandlerTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.354 s -- in com.awscommunity.s3.accesscontrol.PreUpdateHookHandlerTest
[INFO] Running com.awscommunity.s3.accesscontrol.PreCreateHookHandlerTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 s -- in com.awscommunity.s3.accesscontrol.PreCreateHookHandlerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0
[...]
[INFO] --- jacoco:0.8.10:check (jacoco-check) @ awscommunity-s3-accesscontrol-handler ---
[...]
[INFO] Analyzed bundle 'awscommunity-s3-accesscontrol-handler' with 5 classes
[INFO] All coverage checks have been met.
```

## Contract tests excerpts
```
[...]
5 passed, 2 skipped, 17 deselected
[...]
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-21 23:29 UTC, ericzbeard requested changes
Very thorough as always! Only a few minor comments.

Are you going to add this to the pipeline in a separate PR?

2023-09-21 23:29 UTC, ericzbeard commented on hooks/S3_AccessControl/README.md
> +The RPDK will automatically generate the correct hook input model from the schema whenever the project is built via Maven. You can also do this manually with the following command: `cfn generate`.
I don't think "RPDK" is a public term.

2023-09-21 23:29 UTC, ericzbeard commented on hooks/S3_AccessControl/README.md
> +and then submit the hook configuration using the [AWS Command Line Interface (AWS CLI)](https://aws.amazon.com/cli/).  First, get the [Amazon Resource Name](https://docs.aws.amazon.com/general/latest
Replace double spaces after periods with single space. :)

2023-09-22 00:02 UTC, mrinaudo-aws commented on hooks/S3_AccessControl/README.md
> +The RPDK will automatically generate the correct hook input model from the schema whenever the project is built via Maven. You can also do this manually with the following command: `cfn generate`.
I see it described [here](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin#aws-cloudformation-resource-provider-python-plugin-1).  That initial line is actually created by the cfn-cli tool in the README file when you create a new extension project.  I have added lines below for this specific Kotlin project, and left the original line intact.

2023-09-22 01:01 UTC, mrinaudo-aws commented on hooks/S3_AccessControl/README.md
> +and then submit the hook configuration using the [AWS Command Line Interface (AWS CLI)](https://aws.amazon.com/cli/).  First, get the [Amazon Resource Name](https://docs.aws.amazon.com/general/latest
Will do - thank you!

2023-09-22 13:02 UTC, mrinaudo-aws commented on hooks/S3_AccessControl/README.md
> +The RPDK will automatically generate the correct hook input model from the schema whenever the project is built via Maven. You can also do this manually with the following command: `cfn generate`.
I will update this "Hook development notes" section.

2023-09-22 13:52 UTC, mrinaudo-aws commented
> Very thorough as always! Only a few minor comments.
> 
> Are you going to add this to the pipeline in a separate PR?

I can add an updated pipeline template here as well.

2023-09-22 19:21 UTC, ericzbeard approved these changes

2023-09-22 19:21 UTC, merged