Feature/cfwebaclassociation
aws-cloudformation/community-registry-extensions pull request #35
Opened 2022-09-21 15:42 UTC by greengangsta

*Issue #, if available:*

*Description of changes:*

Adding a new resource that can be used to associated a WebACL to a CloudFront distribution, when the CloudFront distribution was created outside of the CloudFormation template. Currently, CloudFormation ‘AWS::WAFv2::WebACLAssociation’ resource has a limitation that a new WebACL provisioned using CloudFormation cannot be associated to an existing CloudFront distribution (created outside of the CloudFormation template). For associating a web ACL to resources in CloudFormation, we can create a resource ‘AWS::WAFv2::WebACLAssociation’. However, this resource type only supports below ResourceArn values for Application Load Balancer, API Gateway and AppSync GraphQL API. Please refer to below documentation link : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webaclassociation.html

To address this, In the handler methods we make API calls to the CloudFront service and update the distribution configuration. The idea is to first fetch the current configuration of the CloudFront distribution by making the get_distribution_config API call , extract the etag value from the response (this value is required to perform the update Distribution API call), make required changes to the current configurations apply the new configuration to the CloudFront distribution by supplying the new configuration object, and etag value in the update_distribution API call.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-21 16:00 UTC, ericzbeard approved these changes

2022-09-22 16:46 UTC, kddejong commented on .gitignore
> +cfassociation.yaml
Seems like an odd root level gitignore

2022-09-22 16:48 UTC, kddejong commented on resources/CloudFront_WebACLAssociation/requirements.txt
> +cloudformation-cli-python-lib>=2.1.9
@ericzbeard do we need a requirements-dev.txt file too

2022-09-22 16:48 UTC, kddejong requested changes
Few questions.

2022-09-23 07:14 UTC, greengangsta commented on .gitignore
> +cfassociation.yaml
removed the gitignore

2022-09-23 09:05 UTC, greengangsta commented
> Few questions.

added code for cicd pipeline and remoted the gitignore

2022-09-23 15:30 UTC, kddejong approved these changes

2022-09-23 15:32 UTC, kddejong requested changes

2022-09-23 15:32 UTC, kddejong commented on .gitignore
> -.tmpenv
Little confusion here.  I was worried about the file that was added to the file not the file itself.

Can we bring this file back with

```
.DS_Store
.tmpenv
```

You may also have to delete the `.DS_Store` file above

2022-09-23 16:23 UTC, kddejong approved these changes

2022-09-23 16:47 UTC, kddejong approved these changes

2022-09-23 17:03 UTC, merged