feat(resource): DynamoDB Item
aws-cloudformation/community-registry-extensions pull request #42
Opened 2022-09-27 22:47 UTC by kddejong

*Issue #, if available:*

*Description of changes:*
- Add a resource for creating records in a DynamoDB table

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-28 14:55 UTC, ericzbeard requested changes
Need setup and integ templates for testing.

2022-09-28 14:55 UTC, ericzbeard commented on resources/DynamoDB_Item/README.md
> +# AwsCommunity::DynamoDB::Item
Readme needs to be done.

2022-09-28 14:55 UTC, ericzbeard commented on resources/DynamoDB_Item/inputs/inputs_1_create.json
> +            "S": "one"}
```suggestion
            "S": "one"
        }
```

2022-09-28 14:55 UTC, ericzbeard commented on resources/DynamoDB_Item/inputs/inputs_1_invalid.json
> +            "S": "one"}
```suggestion
            "S": "one"
        }
```

2022-09-28 14:55 UTC, ericzbeard commented on resources/DynamoDB_Item/inputs/inputs_1_update.json
> +            "S": "one"}
```suggestion
            "S": "one"
        }
```

2022-09-28 14:55 UTC, ericzbeard commented on resources/DynamoDB_Item/src/awscommunity_dynamodb_item/handlers.py
> +            return ProgressEvent.failed(HandlerErrorCode.AlreadyExists, f"item already exists")
Are we expecting that these items will never be changed externally? Drift could be an issue if so.

2022-09-28 14:55 UTC, ericzbeard commented on resources/DynamoDB_Item/src/awscommunity_dynamodb_item/handlers.py
> +
A few comments about what we're doing here would be nice.

2022-10-25 19:54 UTC, kddejong commented on resources/DynamoDB_Item/src/awscommunity_dynamodb_item/handlers.py
> +            return ProgressEvent.failed(HandlerErrorCode.AlreadyExists, f"item already exists")
I don't expect the the PK/SK keys to change.  That would be an entirely new item.

2022-10-25 19:57 UTC, kddejong commented on resources/DynamoDB_Item/src/awscommunity_dynamodb_item/handlers.py
> +
mypy thing.  model.Item could be None which means I want to set a default value if it is.

2023-03-07 06:37 UTC, JobaDiniz commented
This is really needed for dynamodb seed data.
Is this abandoned?

2023-03-07 16:36 UTC, ericzbeard commented
> This is really needed for dynamodb seed data. Is this abandoned?

No it's not, we still plan to finish this up and merge it.

2023-03-09 00:19 UTC, ericzbeard requested changes

2023-03-09 00:19 UTC, ericzbeard commented on resources/DynamoDB_Item/awscommunity-dynamodb-item.json
> +  "description": "This resource will create manage the lifecycle of items in a DynamoDB tableawscommunity-dynamodb-item.json",
Create and manage?

2023-03-09 00:19 UTC, ericzbeard commented on resources/DynamoDB_Item/resource-role-prod.yaml
> +            Condition:
We have to remove the condition in the prod role.

2023-03-09 00:19 UTC, ericzbeard commented on resources/DynamoDB_Item/test/integ.yml
> +    Condition: IsNotProd
What's the point of the condition? Was this copied from DeleteBucketContents?

2023-03-09 00:19 UTC, ericzbeard commented on resources/DynamoDB_Item/awscommunity-dynamodb-item.json
> +    "Item": {
Should this be a map, so multiple key-value-pairs can be added?

2023-03-09 00:27 UTC, kddejong commented on resources/DynamoDB_Item/awscommunity-dynamodb-item.json
> +    "Item": {
Item maps to Attribute which is
```
"Attribute": {
      "patternProperties": {
        "^[A-Za-z0-9_@./#&+-]{1,255}$": {
          "$ref": "#/definitions/AttributeValue"
        }
      },
      "additionalProperties": false
    },
```

This should allow for the map functionality using `patternProperties`

2023-03-09 00:37 UTC, ericzbeard commented on resources/DynamoDB_Item/awscommunity-dynamodb-item.json
> +    "Item": {
We should add multiple items in the sample/integ templates.

2023-03-09 16:57 UTC, ericzbeard approved these changes

2023-03-09 17:22 UTC, merged

2023-03-09 17:46 UTC, JobaDiniz commented
Is this merged? How can I leverage it?

2023-03-09 18:00 UTC, ericzbeard commented
It's merged but not published to the registry yet. If you want to use it now, you would need to clone the repo and do a private registration yourself. Actually it would be great if you could give it a try and see if it meets your needs before we publish!